
services:
  gateway:
    restart: "always"
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - "./client/build/:/app/:rw"
      - "./static:/app/images:rw"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - backend

  backend:
    restart: "always"
    build: "./server"
    env_file: ".env"
    volumes:
      - "./static:/app/static:rw"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    restart: always
    image: "postgres"
    attach: false
    ports:
      - '5000:5432'
    volumes:
      - './postgres:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
